# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: circleci/node:8.15-browsers
      - image: circleci/node:10.15.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Log the current branch
      - run:
        name: Show the current branch
        command: echo ${CIRCLE_BRANCH}

      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Download yarn
      - run:
          name: Install yarn
          command: npm install yarn

      # Download local dependencies
      - run:
          name: Install local dependencies
          command: yarn install

      # Cache local dependencies if they don't exist
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint the source code
      - run:
          name: Linting
          command: npm run lint

      # run tests!
      - run:
          name: Testing
          command: npm rum test-coverage

      # Build project with different configurations based on
      # on the current branch
      - run:
          name: Building
          command: |
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              npm run build-qa
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build-prod
            else
              npm run build-dev

      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dependencies-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          path:
            - dist

#   deploy:
#     docker:
#       - image: circleci/node:10.15.0-browsers
#     working_directory: ~/repo
#     steps:
#       # Steps to be added

# workflows:
#   version: 2
#   # The build and deployment workflow
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy